### ISSUE TITLE
Caged Spider and Spitter are immortal

### ISSUE THREAD

**Issue by voxelit** [UNLV-CS472-672/2024-S-GROUP2-2DRove#56]
The Caged Spider and Spitter mobs are unkillable. I suspect this is because they were based on the finite state machine before Kelvin finished it. I assume the problem may be with the prefabs themselves, but I am not too sure.

This issue is based on the fsmtest branch. If it turns out that I'm blind and the Spitter actually is killable, sorry Yordy lol my bad.

**Comment by Haikp** [comment]
I apologize for the confusion, the issue is that they never actually reach the Hit State, which is where it checks if the mob should be destroyed. This is because the only way that it enters the hit state is if you call EventTrigger(), as a animation event. The NewEnemy.cs script triggers the "Hit" variable in the animator. Where you place the animation event is at the very beginning of the Hit animation.

If you have anymore questions, let me know and I can give a more thorough explanation.

**Comment by YordyCruz** [comment]
Thank you of noticing and figure out the solution to fix this issue. I updated the Spitter and now its killable.

**Comment by voxelit** [comment]
Thank you for fixing the issue! Closing now that it has been resolved.
